server:
  port: 9001

spring:
  application:
    name: nurupo-movie-spark

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: Spark
    author: Zero
