server:
  port: 9001

spring:
  application:
    name: nurupo-movie-recommend
  #Database
  datasource:
    url: jdbc:mysql://localhost:3306/nurupo_recommend?serverTimezone=GMT%2b8
    username: nurupo
    password: nurupo
  #JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  #Timezone
  jackson:
    time-zone: GMT+8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: Spark
    author: Zero
