server:
  port: 8999

spring:
  application:
    name: nurupo-movie-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: API Gateway
    author: Gungnir
